{{- range $name, $cron := .Values.backup.schedule }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ printf "backup-%s-%s" $name (include "gate-teamware.fullname" $) | trunc 52 | trimSuffix "-" }}
  labels:
    {{- include "gate-teamware.labels" $ | nindent 4 }}
    {{- include "gate-teamware.selectorLabels" $ | nindent 4 }}
    app.kubernetes.io/component: backup-{{ $name }}
spec:
  schedule: {{ $cron | quote }}
  {{- if $.Values.backup.concurrencyPolicy }}
  concurrencyPolicy: {{ $.Values.backup.concurrencyPolicy }}
  {{- end }}
  {{- if ne $.Values.backup.failedJobsHistoryLimit "" }}
  failedJobsHistoryLimit: {{ $.Values.backup.failedJobsHistoryLimit }}
  {{- end }}
  {{- if ne $.Values.backup.successfulJobsHistoryLimit "" }}
  successfulJobsHistoryLimit: {{ $.Values.backup.successfulJobsHistoryLimit }}
  {{- end }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "gate-teamware.labels" $ | nindent 12 }}
            {{- include "gate-teamware.selectorLabels" $ | nindent 12 }}
            app.kubernetes.io/component: backup-{{ $name }}
            {{- with $.Values.backup.podLabels }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with $.Values.backup.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        spec:
          serviceAccountName: {{ include "gate-teamware.serviceAccountName" $ }}
          restartPolicy: Never
          containers:
            - name: backup
              image: {{ $.Values.backup.image | quote }}
              imagePullPolicy: {{ $.Values.backup.pullPolicy }}
              env:
              - name: PGHOST
                value: {{ include "postgresql.primary.fullname" $.Subcharts.postgresql | quote }}
              - name: PGPORT
                value: {{ include "postgresql.service.port" $.Subcharts.postgresql | quote }}
              - name: BACKUP_DATABASES
                value: {{ $.Values.postgresql.auth.database | quote }}
              - name: PGUSER
                value: {{ $.Values.postgresql.auth.username | quote }}
              - name: PGPASSWORD
                valueFrom:
                  secretKeyRef:
                    name: {{ include "postgresql.secretName" $.Subcharts.postgresql }}
                    key: password
              {{- if eq $.Values.backup.provider "s3" }}
              - name: RCLONE_CONFIG_STORE_TYPE
                value: s3
              - name: RCLONE_CONFIG_STORE_ENV_AUTH
                value: "true"
              - name: RCLONE_S3_NO_CHECK_BUCKET
                value: "true"
              # Don't double check uploads after completion - this is necessary if
              # our credentials are "write-only" (allowing put but not get)
              - name: RCLONE_S3_NO_HEAD
                value: "true"
              # Skip checksum checks, since these are not compatible with S3 server-side encryption
              - name: RCLONE_IGNORE_CHECKSUM
                value: "true"
              {{- if $.Values.backup.credentialsSecret }}
              - name: AWS_ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    name: {{ $.Values.backup.credentialsSecret | quote }}
                    key: access-key-id
              - name: AWS_SECRET_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: {{ $.Values.backup.credentialsSecret | quote }}
                    key: secret-key
              {{- end }}
              {{- if $.Values.backup.endpoint }}
              - name: AWS_ENDPOINT_URL_S3
                value: {{ $.Values.backup.endpoint | quote }}
              {{- end }}
              {{- if $.Values.backup.region }}
              - name: AWS_REGION
                value: {{ $.Values.backup.region | quote }}
              {{- end }}
              {{- end }}
              - name: UPLOAD_PREFIX
                value: {{ printf "%s%s" (include "gate-teamware.backupPrefix" $) $name | quote }}
              {{- with $.Values.backup.extraEnv }}
              {{- toYaml . | nindent 14 }}
              {{- end }}
              {{- with $.Values.backup.extraArgs }}
              args:
              {{- toYaml . | nindent 14 }}
              {{- end }}
              {{- with $.Values.backup.extraVolumeMounts }}
              volumeMounts:
              {{- toYaml . | nindent 14 }}
              {{- end }}

          {{- with $.Values.backup.extraVolumes }}
          volumes:
          {{- toYaml . | nindent 10 }}
          {{- end }}

---
{{- end }}{{/* range over schedule */}}
