name: Pull Request Checks

on:
  pull_request:
    branches:
      - main

jobs:
  find-charts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR
        uses: actions/checkout@v3

      - name: Find modified charts
        id: changed-charts
        uses: tj-actions/changed-files@v35
        with:
          dir_names: "true"
          dir_names_exclude_root: "true"
          dir_names_max_depth: "1"
          json: "true"

    outputs:
      changed-charts: ${{ steps.changed-charts.outputs.all_changed_files }}

  check-chart:
    runs-on: ubuntu-latest
    needs: find-charts
    strategy:
      matrix:
        chart: ${{ fromJSON(needs.find-charts.outputs.changed-charts) }}

    steps:
      - name: Checkout PR
        uses: actions/checkout@v3

      - name: Lockfile exists for ${{ matrix.chart }}
        run: |
          if yq -e eval .dependencies ${{ matrix.chart }}/Chart.yaml >/dev/null 2>&1 ; then
            if ! [ -f ${{ matrix.chart }}/Chart.lock ] ; then
              echo "Chart ${{ matrix.chart }} has dependencies but no Chart.lock!"
              exit 1
            fi
          else
            echo "Chart ${{ matrix.chart }} has no dependencies, lockfile not required"
          fi

      - name: Version has changed for ${{ matrix.chart }}
        run: |
          if (
            echo "old:"
            git show origin/main:${{ matrix.chart }}/Chart.yaml | sed 's/^/  /'
            echo "new:"
            cat ${{ matrix.chart }}/Chart.yaml | sed 's/^/  /'
          ) | yq -e eval '.old.version != .new.version' - ; then
            echo "Chart version has been updated by this PR"
          else
            echo "PR has modified chart ${{ matrix.chart }} but has not changed the chart version number!"
            exit 1
          fi

      - name: Chart ${{ matrix.chart }} will package correctly
        run: |
          set -e
          cd ${{ matrix.chart }}
          # Add repositories specified in the lock file, so helm dependency build can work
          if [ -f "./Chart.lock" ]; then
            yq --indent 0 '.dependencies | map(["helm", "repo", "add", .name, .repository] | join(" ")) | .[]' "./Chart.lock"  | sh --;
          fi

          helm dependency build
          helm package
